### ISSUE TITLE
js.org subdomain, but not for GitHub page?

### ISSUE THREAD

**Issue by trusktr** [indus/jsorg_layout#1]
Hello Stefan,

Open-source community members and I are making a JavaScript library (the name isn't entirely chosen yet). I don't want to use GitHub pages, but I'd love to have a subdomain on js.org, with my site hosted on my own server at 50.116.4.56. Would that be possible?

Thanks!
- Joe

**Comment by indus** [comment]
In general thats possible, but you should read the other two open issues that deal with the same topic and apply them to your case...

**Comment by indus** [comment]
Edit: I´m referring to the [dns.js.org](https://github.com/js-org/dns.js.org/issues) repo where this issue would fit better.
